import React from 'react'

const Head = () => {
  return (
    <>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </>
  )
}

export default Head